apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: categorizer-worker
spec:
  selector:
    matchLabels:
      app: categorizer-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: categorizer-worker
    spec:
      containers:
      - name: master
        imagePullPolicy: Always
        image: jarvisgaurav98/oms-categorizer-worker:latest
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 4000
        envFrom:
          - secretRef:
              name: oms-secrets