kind: Service
apiVersion: v1
metadata:
  name: "rabbitmq"
spec:
  type: NodePort
  selector:
    app: "rabbitmq"
  ports:
    - protocol: TCP
      port: 15672
      nodePort: 30672
      targetPort: 15672
      name: http
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp